### ISSUE TITLE
Release 4.3.0

### ISSUE THREAD

**Issue by rahulporuri** [enthought/codetools#23]
Release a new version of codetools, which now supports Python 3.

**Comment by rahulporuri** [comment]
@corranwebster the enthought oss maintainers doc lists you as the maintainer. do you have any bandwidth for this?

**Comment by corranwebster** [comment]
Not today, but possibly within the next week.  Or alternatively, if you would like to do it I can provide guidance.

**Comment by rahulporuri** [comment]
> Not today, but possibly within the next week. Or alternatively, if you would like to do it I can provide guidance.

It doesn't need to happen today. I can do it with your guidance early next week. Thanks :)

**Comment by corranwebster** [comment]
If you want to do the majority of the release, the documentation for the process is here: https://github.com/enthought/documentation/blob/master/source/guidelines/ets_maintenance.rst (possibly should move that to a public repo).

I can review PRs and double-check things for you.
