### ISSUE TITLE
DataContext instances are unhashable.

### ISSUE THREAD

**Issue by rahulporuri** [enthought/codetools#24]
After PR #22 , the `codetools.contexts.data_context.DataContext` became unhashable. Not sure it should have been hashable in the first place as it provides a MutableMapping interface. See https://github.com/enthought/codetools/pull/22/files#diff-56a8eaf9ff82b992cac3df10a20494b8 for changes made to the module in PR #22

**Comment by rkern** [comment]
They should not have been, no, which is why I made that change.

See https://github.com/enthought/traits/pull/410 for the associated fix in `traits` that removes the spurious requirement for `HasTraits` instances to be hashable.
