### ISSUE TITLE
test_block.test_basic_01 ? missing call to raise SkipTest

### ISSUE THREAD

**Issue by idella** [enthought/codetools#3]
All tests in test_block.py begin with a call to raise  SkipTest, but for the first, test_basic_01.
Sure enough it's the only test to fail.  When patched to match all others it passes.
Was this an oversight?

> > > Source compiled.
> > > - Testing of dev-python/codetools-4.0.0 with CPython 2.6 skipped
> > > - Testing of dev-python/codetools-4.0.0 with CPython 2.7...
> > >   PYTHONPATH=build-2.7/lib nosetests --verbosity=1
> > >   ................FSSSSSS...............................................................................................................................................................................................................................................................
> > >   ======================================================================
> > >   FAIL: Test basic use of a Block.
> > >   ----------------------------------------------------------------------
> > >   Traceback (most recent call last):
> > >   File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
> > >     self.test(*self.arg)
> > >   File "/var/tmp/portage/dev-python/codetools-4.0.0/work/codetools-4.0.0/codetools/blocks2/tests/test_block.py", line 14, in test_basic_01
> > >     assert_equal(b.inputs, set([]))
> > >   AssertionError: Items in the first set but not the second:
> > >   'y'
> > >   'x'

@@ -9,6 +9,9 @@

 def test_basic_01():
     """Test basic use of a Block."""
+
-    raise SkipTest
  +
   code = 'x = 100\ny = x + 1'
   b = Block(code)
   assert_equal(b.inputs, set([]))

sees it pass

**Comment by mdickinson** [comment]
Closing as out of date: the `blocks` machinery has not been ported to Python 3, and probably won't be.
