### ISSUE TITLE
Remove import-time registration of adaptation offers

### ISSUE THREAD

**Issue by mdickinson** [enthought/codetools#57]
`data_context.py` and `i_context.py` do import-time registration of adaptation offers, noted in comments as "for backwards compatibility". This is potentially problematic for projects (and tests) that might switch out the global adaptation manager for a different one, since it then becomes unpredictable - depending on import time - which adaptation manager the codetools offers get registered in. I'd like to remove these import-time registrations.

https://github.com/enthought/codetools/blob/20d8bb1eba68145750a1b689655b839078121474/codetools/contexts/data_context.py#L391-L393

https://github.com/enthought/codetools/blob/20d8bb1eba68145750a1b689655b839078121474/codetools/contexts/i_context.py#L269-L271

I believe that codetools has essentially only one downstream user at this point, and a recent PR on that project removes the need for the import-time registered adaptation offers.

**Comment by mdickinson** [comment]
Another motivation for doing this: this import-time registration led (in a real project) to hard-to-diagnose "dictionary changed size" warnings from Traits. What was happening was that the imports were being triggered (as a result of adaptation protocols specified as strings rather than objects) during processing of adaptation offers.

**Comment by corranwebster** [comment]
I think this is safe to do.
